using System.Reflection;
[assembly: AssemblyTitle("AdsClient.Wrap")]
[assembly: AssemblyDescription("Wrapper for ADS.API")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("AdsClient.Wrap")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.1")]
