language: csharp
solution: ./src/AdsClient.sln
install:
  - nuget restore ./src/AdsClient.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./src/AdsClient.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/AdsClient.Test/bin/Release/AdsClient.Test.dll